###
# login 
POST  http://localhost:5000/login/
Content-Type: application/json

{
     "email": "pandhu@gmail.com", 
     "password": "admin"
}
###
# Get All 
GET  http://localhost:5000/user/getAll
Content-Type: application/json